### ISSUE TITLE
I want to add png rgb 16 bits option for rife ncnn vulkan

### ISSUE THREAD

**Issue by bukhalmae145** [TNTwise/rife-ncnn-vulkan#2]
From ./build/main.cpp code, where should I modify to earn 16 bit depth option for png or webp?

<img width="719" alt="Screenshot 2024-02-14 at 2 43 31 PM" src="https://github.com/TNTwise/rife-ncnn-vulkan/assets/63964886/fb4865c3-27b6-4814-bf88-59468db7dc49">
And what does timestep option does?

**Comment by TNTwise** [comment]
Please open the issue in the parent repository. This is a fork to add new models. I don't maintain the code in this repo, nor can I read C/CPP, so I can't answer.

**Comment by bukhalmae145** [comment]
> Please open the issue in the parent repository. This is a fork to add new models. I don't maintain the code in this repo, nor can I read C/CPP, so I can't answer.

Well, I got this code while I did the Build With CMake procedure from this repository.

**Comment by TNTwise** [comment]
I can't answer you though, this is just for added models, I didn't write the code.
