### ISSUE TITLE
layer MemoryData not exists or registered

### ISSUE THREAD

**Issue by NenelFX** [TNTwise/rife-ncnn-vulkan#5]
Hello, I use a plugin "RIFE.dll" from vapoursynth
from "HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan"
But this project has been discontinued from github.
it even supports the "rife-v4.6" model, from then on, no other works. the error "layer MemoryData not exists or registered" appears

and "librife.dll" from "styler00dollar/VapourSynth-RIFE-ncnn-Vulkan"
It doesn't work on my PC, the problem could be that my CPU or GPU are incompatible with "librife.dll" I already spoke to him but I couldn't resolve it.

Your application works perfectly on my PC, all models work.

But in the vapoursynth plugin "RIFE.dll", the models from "rife-v4.7" below do not always work and it appears "layer MemoryData not exists or registered"

I've been waiting all this time for "nihui/rife-ncnn-vulkan" to have a new version but I'm still waiting.

If it were possible, I would like you to adapt the "rife-v4.8" model so that the error "layer MemoryData not exists or registered" does not appear
If it is not possible, please let me know

**Comment by TNTwise** [comment]
Eliminating memorydata is not impossible, as nihui did it for 4.6, which when you export regularly it has memorydata.  I don't know how nihui removed memorydata, as it was removed from the .bin file itself. I won't look into this, as I do not have the knowledge of ncnn, or the time to learn. Vapoursynth rife ncnn should work though, if not try an older version of it. 

Older versions can work with newer models with the model_path parameter
